name: test
on: 
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - run: make test

  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - run: make coverage
      - run: bash <(curl -s https://codecov.io/bash)
